// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ujNRi14vh6PnX2hFVzvY1ctK7_1tDhE',
    appId: '1:670503199228:web:cb583869381d2b45749279',
    messagingSenderId: '670503199228',
    projectId: 'senhong-37272',
    authDomain: 'senhong-37272.firebaseapp.com',
    storageBucket: 'senhong-37272.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BA04dQkGpeG_rZvumDdgtsv-32ebNlI',
    appId: '1:670503199228:android:4edc03a7df25d4e8749279',
    messagingSenderId: '670503199228',
    projectId: 'senhong-37272',
    storageBucket: 'senhong-37272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7DJ-MIu-oWM3ZLlgYcMNfu1oij4MwDs',
    appId: '1:670503199228:ios:ef7ce4909fe6b176749279',
    messagingSenderId: '670503199228',
    projectId: 'senhong-37272',
    storageBucket: 'senhong-37272.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7DJ-MIu-oWM3ZLlgYcMNfu1oij4MwDs',
    appId: '1:670503199228:ios:ef7ce4909fe6b176749279',
    messagingSenderId: '670503199228',
    projectId: 'senhong-37272',
    storageBucket: 'senhong-37272.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ujNRi14vh6PnX2hFVzvY1ctK7_1tDhE',
    appId: '1:670503199228:web:9f92350eed32008c749279',
    messagingSenderId: '670503199228',
    projectId: 'senhong-37272',
    authDomain: 'senhong-37272.firebaseapp.com',
    storageBucket: 'senhong-37272.appspot.com',
  );
}
